from typing import Protocol


class MetricsPort(Protocol):
    def record_request(self, model: str, tenant: str = "default") -> None: ...

    def record_latency(self, model: str, seconds: float) -> None: ...

    def record_tokens(self, model: str, token_type: str, count: int) -> None: ...

    def record_error(self, error_type: str, model: str = "unknown") -> None: ...

    def record_guardrail(self, rule: str) -> None: ...
